# Generated by Django 4.2.5 on 2023-10-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
